name: Change the name
description: "description"
author: ""
branding:
  icon: upload
  color: blue
inputs:
  github_token:
    required: true
    description: "token to access Github API"
  packages:
    required: false
    description: Comma separated list of packages to check for updates
  branch_prefix:
    required: false
    description: Prefix to use for release branches
  base_branch:
    required: false
    description: Branch to merge release branch into, defaults to the default branch
runs:
  using: "node18"
  main: "dist/index.js"
